"""
Команды для пуша на новом репозитории

git init

git add .

git commit -m "First Commit"

git remote add origin <ссылка на репозиторий>

git status

git branch

git branch -M main

git push -u origin main

"""


"""
Команды для пуша на старом репозитории

git add .

git commit -m "second commit"

git push

"""


"""
Работа с ветками

git branch

git branch -M main

git checkout -b test

git checkout test


"""